### ISSUE TITLE
Any chance of supporting Java 8?

### ISSUE THREAD

**Issue by jblayneyXpanxion** [chrisgleissner/spring-batch-rest#11]
Would be great if you could support back to Java 8. Possible?

**Comment by chrisgleissner** [comment]
Hi,

I think this should be fairly straightforward since none of the code
depends on API features only introduced after Java 8.

Have you tried building from source under Java 8 and using the resulting
Jar in your environment?  It may well boil down to changing the maven
compiler plugin settings to target version 1.8 instead of 11.

Thanks
Christian

**Comment by chrisgleissner** [comment]
Released JDK 8 compatible version 1.4.1

**Comment by jblayneyXpanxion** [comment]
Thank you so much for this, it works!

**Comment by chrisgleissner** [comment]
That's great! You are welcome.
