### ISSUE TITLE
JobConfig adaptations

### ISSUE THREAD

**Issue by jmformenti** [chrisgleissner/spring-batch-rest#9]
Hi,

 I want to propose 2 changes in `JobConfig` class, if possible:

1. In my project I have to use `jackson-core:2.9.9` to work properly with other dependencies. To avoid an exception in that version, `JobConfig` needs `@NoArgsConstructor` and `@AllArgsConstructor` annotations. Could be added?

2. All the properties in `JobConfig` are `String` values (`Map<String, String> properties`), could you allow other types (i.e `Map<String, Object> properties`) ?

**Comment by chrisgleissner** [comment]
Hi,

good idea. I will add this soon. 

Thanks
Christian

**Comment by jmformenti** [comment]
Thanks to you for sharing this great project!

**Comment by chrisgleissner** [comment]
You are welcome. I have now implemented your suggestion. 

The ` JobConfig` now supports `Map<String, Object> properties`. If the values of this map are of type `Double`, `Date`, or `Long`, they are cast accordingly and passed to a new `JobParameters` instance. Otherwise, the value is turned into a `String` via its `toString()` method, and this is then used in the `JobParameters` instance. This is because `JobParameters` only supports the aforementioned types via its constructors.

This is now part of release 1.4.0.

**Comment by jmformenti** [comment]
Thanks!
